### ISSUE TITLE
[BUG]: Login & SignUp Functionality

### ISSUE THREAD

**Issue by arcVaishali** [Vidip-Ghosh/CertVault#6] opened 2023-10-03 16:18 UTC
Whenever a user tries to signup using his credentials and clicks on **SignUp**, its not able to redirect him/her towards dashboard. More precisely a ```log undefined``` error logs in the terminal each time user tries signing up.

**Comment by Dineshraju3435** [comment] 2023-10-03 16:43
hey , This is dinesh and  I am new for open source, what exactly is the bug like what should we do for the above question?

**Comment by Vidip-Ghosh** [comment] 2023-10-03 16:49
https://github.com/Vidip-Ghosh/CertVault/assets/91741581/b1d272b9-be5b-47f5-a327-fdf40c4bf09d

See @Dineshraju3435 actually, when we click on signup, it should redirect to dashboard. 
But its not working as expected & throwing undefined in console.

**Comment by Thehackerash** [comment] 2023-10-03 17:52
please assign this issue to me

**Comment by Vidip-Ghosh** [comment] 2023-10-03 18:02
@Dineshraju3435 Would you like to work? If yes, please let me know. 
Or 
can I assign this issue @Thehackerash ?

**Comment by Thehackerash** [comment] 2023-10-03 18:04
I will try my bestt...

**Comment by Vidip-Ghosh** [comment] 2023-10-03 18:08
@Thehackerash go for it. 
All the best.

**Comment by p7uverma** [comment] 2023-10-04 04:04
I fixed it

**Comment by Vidip-Ghosh** [comment] 2023-10-04 04:32
@Thehackerash  apologize to state that the issue is already been solved by @p7uverma 
But @Thehackerash you can still contribute & if you get any issue OR want to add feature. Please feel free to create issue & get assigned.

**Closed** 2023-10-04 04:34 UTC
Labels: bug, good first issue, hacktoberfest
